export const cars = [{"id":1,"model":"XK Series","last_name":"Jaguar"},
{"id":2,"model":"Skylark","last_name":"Buick"},
{"id":3,"model":"Prius","last_name":"Toyota"},
{"id":4,"model":"SLR McLaren","last_name":"Mercedes-Benz"},
{"id":5,"model":"Firebird","last_name":"Pontiac"},
{"id":6,"model":"Neon","last_name":"Dodge"},
{"id":7,"model":"Ram Van 1500","last_name":"Dodge"},
{"id":8,"model":"Econoline E350","last_name":"Ford"},
{"id":9,"model":"Corolla","last_name":"Toyota"},
{"id":10,"model":"Camry","last_name":"Toyota"},
{"id":11,"model":"Cayenne","last_name":"Porsche"},
{"id":12,"model":"Century","last_name":"Buick"},
{"id":13,"model":"T100 Xtra","last_name":"Toyota"},
{"id":14,"model":"Silverado","last_name":"Chevrolet"},
{"id":15,"model":"Insight","last_name":"Honda"},
{"id":16,"model":"Alcyone SVX","last_name":"Subaru"},
{"id":17,"model":"Bravada","last_name":"Oldsmobile"},
{"id":18,"model":"S2000","last_name":"Honda"},
{"id":19,"model":"Maxima","last_name":"Nissan"},
{"id":20,"model":"Charger","last_name":"Dodge"},
{"id":21,"model":"Cabriolet","last_name":"Volkswagen"},
{"id":22,"model":"Ranger","last_name":"Ford"},
{"id":23,"model":"Th!nk","last_name":"Ford"},
{"id":24,"model":"Blazer","last_name":"Chevrolet"},
{"id":25,"model":"Aura","last_name":"Saturn"},
{"id":26,"model":"Sportage","last_name":"Kia"},
{"id":27,"model":"Sequoia","last_name":"Toyota"},
{"id":28,"model":"Neon","last_name":"Dodge"},
{"id":29,"model":"Terraza","last_name":"Buick"},
{"id":30,"model":"S-Series","last_name":"Saturn"},
{"id":31,"model":"RX-7","last_name":"Mazda"},
{"id":32,"model":"Silverado","last_name":"Chevrolet"},
{"id":33,"model":"Galant","last_name":"Mitsubishi"},
{"id":34,"model":"Armada","last_name":"Nissan"},
{"id":35,"model":"Compass","last_name":"Jeep"},
{"id":36,"model":"GT500","last_name":"Ford"},
{"id":37,"model":"SJ","last_name":"Suzuki"},
{"id":38,"model":"F-350 Super Duty","last_name":"Ford"},
{"id":39,"model":"Viper","last_name":"Dodge"},
{"id":40,"model":"Grand Marquis","last_name":"Mercury"},
{"id":41,"model":"Express 2500","last_name":"Chevrolet"},
{"id":42,"model":"Grand Cherokee","last_name":"Jeep"},
{"id":43,"model":"Legacy","last_name":"Subaru"},
{"id":44,"model":"Tacoma","last_name":"Toyota"},
{"id":45,"model":"Sedona","last_name":"Kia"},
{"id":46,"model":"Explorer Sport Trac","last_name":"Ford"},
{"id":47,"model":"Corvette","last_name":"Chevrolet"},
{"id":48,"model":"Cherokee","last_name":"Jeep"},
{"id":49,"model":"CL-Class","last_name":"Mercedes-Benz"},
{"id":50,"model":"Bel Air","last_name":"Chevrolet"}]

export const companysData = [{"id":1,"model":"Gabtype","last_name":"Philippines"},
{"id":2,"model":"Plajo","last_name":"Portugal"},
{"id":3,"model":"Dynabox","last_name":"Philippines"},
{"id":4,"model":"Brightdog","last_name":"Slovenia"},
{"id":5,"model":"Skaboo","last_name":"Honduras"},
{"id":6,"model":"Shuffletag","last_name":"South Africa"},
{"id":7,"model":"Wikizz","last_name":"Belarus"},
{"id":8,"model":"Browsecat","last_name":"China"},
{"id":9,"model":"Skyndu","last_name":"China"},
{"id":10,"model":"Shuffledrive","last_name":"Ukraine"},
{"id":11,"model":"Twitternation","last_name":"Russia"},
{"id":12,"model":"Viva","last_name":"Russia"},
{"id":13,"model":"Thoughtsphere","last_name":"Chad"},
{"id":14,"model":"Latz","last_name":"China"},
{"id":15,"model":"Voomm","last_name":"Japan"},
{"id":16,"model":"Aimbo","last_name":"Indonesia"},
{"id":17,"model":"Yotz","last_name":"Indonesia"},
{"id":18,"model":"Kazio","last_name":"China"},
{"id":19,"model":"Fadeo","last_name":"Poland"},
{"id":20,"model":"Bluejam","last_name":"Poland"},
{"id":21,"model":"Devpulse","last_name":"Indonesia"},
{"id":22,"model":"Jaxspan","last_name":"China"},
{"id":23,"model":"Zazio","last_name":"Russia"},
{"id":24,"model":"Tagcat","last_name":"Indonesia"},
{"id":25,"model":"Wikivu","last_name":"China"},
{"id":26,"model":"Ainyx","last_name":"Philippines"},
{"id":27,"model":"Jaloo","last_name":"Russia"},
{"id":28,"model":"Katz","last_name":"China"},
{"id":29,"model":"Trudeo","last_name":"United States"},
{"id":30,"model":"Skyvu","last_name":"Poland"},
{"id":31,"model":"Zooxo","last_name":"Philippines"},
{"id":32,"model":"Fivechat","last_name":"Indonesia"},
{"id":33,"model":"Divape","last_name":"Lebanon"},
{"id":34,"model":"Photolist","last_name":"Portugal"},
{"id":35,"model":"Dabjam","last_name":"France"},
{"id":36,"model":"Shuffledrive","last_name":"Canada"},
{"id":37,"model":"Devpulse","last_name":"Philippines"},
{"id":38,"model":"Lazzy","last_name":"Canada"},
{"id":39,"model":"Plajo","last_name":"New Zealand"},
{"id":40,"model":"Feedfish","last_name":"Russia"},
{"id":41,"model":"Dabvine","last_name":"American Samoa"},
{"id":42,"model":"Skimia","last_name":"China"},
{"id":43,"model":"Feedfish","last_name":"China"},
{"id":44,"model":"Feedmix","last_name":"Iran"},
{"id":45,"model":"Oyoba","last_name":"Philippines"},
{"id":46,"model":"Demizz","last_name":"China"},
{"id":47,"model":"Wordtune","last_name":"Colombia"},
{"id":48,"model":"Abatz","last_name":"Brazil"},
{"id":49,"model":"Camido","last_name":"Indonesia"},
{"id":50,"model":"Youspan","last_name":"Ukraine"}]